Algoritmo "EX-D"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson Costa Dos Santos
// Descrição   : exibe os numeros impares até o 20
// Autor(a)    : Isaac Martins
// Data atual  : 30/03/2024
Var

   soma, numero,impar: inteiro

Inicio
   numero <- 0
   enquanto numero <= 19 faca
      numero <- numero + 1
      se numero % 2 <> 0 entao
         escreva(numero)
      fimse
   fimenquanto
Fimalgoritmo