Algoritmo "EX-K"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson
// Descrição   : Apresenta um valor se ele for menor ou igual a 3
// Autor(a)    : Isaac Martins
// Data atual  : 17/04/2024
Var
   numero: inteiro
Inicio
   escreva ("Digite um número: ")
   leia (numero)

   se numero <= 3 entao
      escreval ("Apresentando o número:", numero)
   fimse
Fimalgoritmo