Algoritmo "EX-A"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Quadrado dos números inteiros de 15 a 200
// Autor(a)    : Isaac Martins
// Data atual  : 16/04/2024
Var
   contadora,resultado:inteiro
Inicio
   para contadora de 15 ate 200 passo 1 faca
      resultado <- contadora * contadora
      escreval(contadora, " ^ 2 =", resultado)
   fimpara
Fimalgoritmo