Algoritmo "EX-B"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Retorna a tabuado do valor inserido até 10
// Autor(a)    : Isaac Martins
// Data atual  : 16/04/2024
Var
   valor,contadora,resultado:inteiro
Inicio
   escreva ("Digite um valor: ")
   leia (valor)

   para contadora de 0 ate 10 passo 1 faca
      resultado <- valor * contadora
      escreval (valor, " *", contadora, " =", resultado)
   fimpara
Fimalgoritmo