Algoritmo "EX-C"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Soma dos 100 primeiros números inteiros
// Autor(a)    : Isaac Martins
// Data atual  : 16/04/2024
Var
   contadora,soma:inteiro
Inicio
   para contadora de 1 ate 100 passo 1 faca
      soma <- soma + contadora
   fimpara
   
   escreval ("A soma dos 100 primeiros números inteiros é: ",soma)
Fimalgoritmo