Algoritmo "EX-E"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Informa os números ímpares de 1 até 20
// Autor(a)    : Isaac Martins
// Data atual  : 16/04/2024
Var
   contadora:inteiro
Inicio
   para contadora de 1 ate 20 passo 1 faca
      se contadora % 2 = 1 entao
         escreval ("Números ímpares de 1 até 20:", contadora)
      fimse
   fimpara
Fimalgoritmo