Algoritmo "EX-F"
// Disciplina  : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Apresenta os valores divisíveis por 4 até 200
// Autor(a)    : Isaac Martins
// Data atual  : 16/04/2024
Var
   contadora:inteiro
Inicio
   para contadora de 1 ate 200 passo 1 faca
      se contadora % 4 = 0 entao
         escreval (contadora)
      fimse
   fimpara
Fimalgoritmo