Algoritmo "EX-A"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson
// Descrição   : Conversão de temperatura, de Celsius para Fahrenheit.
// Autor(a)    : Isaac Martins
// Data atual  : 09/04/2024
Var
   celsius: real
   fahrenheit: real
Inicio
   escreva ("Digite a temperatura em Graus Celsius: ")
   leia (celsius)
   fahrenheit <- (9 * celsius + 160) / 5
   escreval (celsius, "°C , em ºF é:", fahrenheit, "ºF")
Fimalgoritmo