Algoritmo "EX-C"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Calcula o volume de uma lata
// Autor(a)    : Isaac Martins
// Data atual  : 09/04/2024
Var
   raio:real
   altura:real
   volume:real
Inicio
   escreva("Escreva o raio da lata: ")
   leia(raio)
   escreva("Escreva a altura da lata: ")
   leia (altura)
   volume <- 3.14 * raio ^ 2 * altura
   escreva ("O volume da lata é: ", volume)
Fimalgoritmo