Algoritmo "EX-A"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa
// Descrição   : Apresenta os Quadrados dos números inteiros
// Autor(a)    : Isaac
// Data atual  : 05/04/2024
Var
   // Seção de Declarações das variáveis
   numero: inteiro

Inicio
   numero <- 15
   repita
      Escreval(numero * numero)
      numero <- numero + 1
   ate numero > 200
Fimalgoritmo